import {FC, default as React} from "react";
import "./PlixEditor.scss";
import {SplitTopBottom} from "../divider/SplitTopBottom";
import {SplitLeftRight} from "../divider/SplitLeftRight";
import {TreeTimeline} from "./TreeTimeline";

export const PlixEditor: FC = () => {
    return (
        <div className="plix-editor">
            <SplitTopBottom minTop={100} minBottom={200} storageKey="s1">
                <TreeTimeline />
                <SplitLeftRight minLeft={200} minRight={200} storageKey="s3">
                    <div style={{backgroundColor: "#ffd", width: "100%"}}>
                        SIMPLE PROPS-EDITOR<br/>
                        SIMPLE PROPS-EDITOR<br/>
                        SIMPLE PROPS-EDITOR<br/>
                        SIMPLE PROPS-EDITOR<br/>
                    </div>
                    <SplitTopBottom minTop={100} minBottom={100} storageKey="s4">
                        <div style={{backgroundColor: "#fdf", width: "100%"}}>CANVAS-TOP</div>
                        <SplitLeftRight minLeft={100} minRight={100} storageKey="s5">
                            <div style={{backgroundColor: "#ddf", width: "100%"}}>CANVAS-1</div>
                            <div style={{backgroundColor: "#fdd", width: "100%"}}>CANVAS-2</div>
                        </SplitLeftRight>
                    </SplitTopBottom>
                </SplitLeftRight>
            </SplitTopBottom>
        </div>
    )
}

/**

 <SplitLeftRight minLeft={200} minRight={200} storageKey="s2">
 <div style={{backgroundColor: "#dff", width: "100%"}}>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 TREE_TREE_TREE_TREE_TREE<br/>
 </div>
 <div style={{backgroundColor: "#dfd", width: "100%"}}>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
 </div>
 </SplitLeftRight>


 */