import {FC, default as React} from "react";
import "./PlixEditor.scss";
import {SplitTopBottom} from "../divider/SplitTopBottom";
import {SplitLeftRight} from "../divider/SplitLeftRight";

export const PlixEditor: FC = () => {
    return (
        <div className="plix-editor">
            <SplitTopBottom minTop={100} minBottom={100} storageKey="row1">
                <SplitLeftRight minLeft={200} minRight={200} storageKey="col1">
                    <div style={{backgroundColor: "#fdd", width: "100%"}}>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                        TREE_TREE_TREE_TREE_TREE<br/>
                    </div>
                    <div style={{backgroundColor: "#dfd", width: "100%"}}>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                        TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_TIMELINE_<br/>
                    </div>
                </SplitLeftRight>
                <div style={{overflow: "auto"}}>
                    BOTTOM-BOTTOM<br/>
                    BOTTOM-BOTTOM<br/>
                    BOTTOM-BOTTOM<br/>
                    BOTTOM-BOTTOM<br/>
                    BOTTOM-BOTTOM<br/>
                    BOTTOM-BOTTOM<br/>
                    BOTTOM-BOTTOM<br/>
                    BOTTOM-BOTTOM<br/>
                    BOTTOM-BOTTOM<br/>
                    BOTTOM-BOTTOM<br/>
                    BOTTOM-BOTTOM<br/>
                </div>
            </SplitTopBottom>
        </div>
    )
}